# Site settings
title: Redhcp
description: Theme Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000"

# User settings
username: "Hi, I'm Cesar"
#user_description: lorem_ipsum
user_title: Technical Support Engineer
email: Th3Ces4r@gmail.com
twitter_username: Th3Ces4r
github_username: redhcp
linkedin_username: cyl90
devto_username: redhcp
status_page_link: "https://redhcp.site/status-page/"
docs_link: "https://redhcp.site/docs/menu_long/"

exclude: ["package.json", "src", "node_modules"]
