# Site settings
title: Redhcp
description: Theme Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Redhcp
user_description: lorem_ipsum
user_title: Systems Analyst
email: a@a.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum

exclude: ["package.json", "src", "node_modules"]
